 
server {
    listen 8080;
    server_name localhost;
    client_max_body_size 100000000;

    root src/www;
    # / must answer to GET request ONLY
    location / {
        index index.html;
        methods GET;
    }

    # /directory/ must answer to GET request, root is YoupiBanane, default to youpi.bad_extension
    location /directory {
        root YoupiBanane;
        index youpi.bad_extension;
        methods GET POST; 
        
        # Any file with .bla as extension must answer to POST request by calling the cgi_test executable
        cgi bla ./ubuntu_cgi_tester;
    }

    # /post_body must answer anything to POST request with a maxBody of 100
    location /post_body {
        root www/html; 
        methods POST;
    }

    # (Keep your standard upload location if you still need it for your own tests)
    location /upload {
        root www/html;
        upload_path www/var/uploads;
        methods GET POST DELETE;
    }
}