# Server 1: Standard Web Server
server {
	listen 8080;
	listen 127.0.0.1:9090;
	server_names webserv.com www.webserv.com;
    
	root /var/www/html;
	client_max_body_size 100M;
    
	# Testing your multi-code error page logic
	error_pages 400 401 404 405 /errors/40x.html;
	error_pages 500 502 503 504 /errors/50x.html;

	# Testing root inheritance
	location / {
		methods GET;
		index index.html;
		autoindex on;
	}

	# Testing POST and Uploads
	location /upload {
		methods POST;
		upload_path /var/www/uploads;
	}

	# Testing CGI logic with multiple handlers
	location /cgi-bin {
		root /var/www/cgi;
		cgi .py /usr/bin/python3;
		cgi .php /usr/bin/php-cgi;
	}

	# Testing Redirection
	location /old-page {
		return_code 301;
		return_url http://newsite.com/home;
	}
}

# Server 2: Minimal Server for Testing Defaults
server {
	listen 7070;
	server_names test_server;
	root /tmp;

	location /tmp {
		autoindex on;
		methods GET POST DELETE;
	}
}